version: "3"
services:
  app:
    depends_on:
      - db
    links:
      - db
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    tty: true
    env_file:
      - .env

  db:
    container_name: dockerDB
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
#      MARIADB_HOSTNAME: dockerDB
      MARIADB_USER: hackathon_23_winter_12
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: hackathon_23_winter_12
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/mysql
