from openai import OpenAI
import time
import re
import json
import requests

# Parameters
MAX_RETRIES = 3


def query_gpt(client, prompt):
    """
    Send the given prompt to the GPT api to get a completion.

    Parameters
    ----------
    client: ?
        OpenAI client
    prompt: str
        prompt to generate a recipe

    Returns
    -------
    recipe_info: dict
        dict that contains information about the recipe other than the image
    image_prompt: str
        prompt to generate image
    """
    return recipe_info, image_prompt


def query_dall_e(client, prompt):
    """
    Send the given prompt to dall-e-3 api to get an image.

    Parameters
    ----------
    client: ?
        OpenAI client
    prompt: str
        prompt for generating image generated by query_gpt

    Returns
    -------
    image_url: str
        url to retrieve the image generated by dall-e-3
    """
    return image_url


def get_image_from_url(url):
    """
    The image generated by Dall-e-3 is downloaded by the specified url and changed to binary data.

    Parameters
    ----------
    url

    Returns
    -------
    binary_image: binary
        binary image retrieved from the given url
    """
    return binary_image


def executor(name):
    """
    Generates a recipe and image from a given dish name and returns them in dict.

    Parameters
    ----------
    name: str

    Returns
    -------
    recipe_info: dict
        dict with cooking_name, comment, ingredient, seasoning, instruction, and image as keys
    """
    client = OpenAI()  # if you find it more convenient to use a global variable, please change it.

    recipe_info, image_prompt = query_gpt(client, name)
    image_url = query_dall_e(client, image_prompt)

    recipe_info['image'] = get_image_from_url(image_url)

    return recipe_info
